import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@parkease/ui/src/app/globals.css';
import ApolloClientProvider from '@parkease/ui/src/components/molecules/ApolloClientProvider';
import SessionProvider from '@parkease/ui/src/components/molecules/SessionProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <SessionProvider>
        <ApolloClientProvider>
          <body className={inter.className}>{children}</body>
        </ApolloClientProvider>
      </SessionProvider>
    </html>
  );
}
